# name: AppEngine Deployment

# on:
#   push:
#     branches:
#       -master

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
    
#     steps:
#     - name: Setting up GCloud Auth
#         uses: actions/auth@master
#         env:
#           GCLOUD_AUTH: ${{ secrets.GCLOUD_AUTH }}
#     - name: Run deployment
#       uses: actions/cli@master
#       run: gcloud app deploy ./front_end_app.yaml --quiet
